# Generated by Django 5.0.3 on 2024-03-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('pricePerNight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spots', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('role', models.CharField(choices=[('AGENT', 'Agent'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
            ],
        ),
    ]
